
swagger: '2.0'

info:
  version: "0.0.6"
  title: RIHA-API
  description: Liides andmete avaldamiseks Riigi Infosüsteemi osiste kohta. Iga Riigi Infosüsteemi mõnd osa haldav asutus publitseerib info tema valduses olevate süsteemide ning registrite kohta vähemalt ühes RIHA-API instantsis. Liidese võtmesõnad on rahvusvahelise koosvõime huvides ingliskeelsed. 
  license:
    name: MIT
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /systems.json:
    get:
      description: Tagastab nimekirja käesolevale instantsile teadaolevatest infosüsteemidest
      responses:
        '200':
          description: Kõik läks hästi
          schema:
            type: array
            items:
              $ref: '#/definitions/system'

  /{shortname}:
    get:
      description: Tagastab info konkreetse infosüsteemi kohta. Koos API URLiga on ühtlasi tegu süsteemi unikaalse identifikaatoriga
      parameters:
        - name: shortname
          in: path
          description: Viidatava infosüsteemi lühinimi
          required: true
          type: string
      responses:
        '200':
          description: Süsteem leidus, info tagastatakse
          schema:
            $ref: '#/definitions/detailed_system'
        '404':
          description: Sellenimelist süsteemi ei leidu
  
definitions:
  system:
    description: Süsteemi lühiandmestik. Andmed, mis on peamiselt olulised süsteemi elutsükli mõttes
    type: object
    properties:
      name:
        type: string
        description: Süsteemi täispikk, ametlik, nimi
      shortname:
        type: string
        description: Süsteemi lühinimi
      owner:
        type: object
        properties:
          code:
            type: string
            description: Süsteemi vastutava töötleja registrikood
          name:
            type: string
            description: Süsteemi vastutava töötleja nimi
      documentation:
        type: string
        description: URL, mis viitab süsteemi dokumentatsiooni avalikule asukohale
      meta:
        type: object
        properties:
          system_status:
            type: object
            description: Süsteemi olek
            properties:
              status: 
                type: string
                description: Staatuse tekstiline kirjeldus
              timestamp:
                type: string
                format: date-time
                description: Staatuse saamise aeg
          approval_status:
            type: object
            description: Süsteemi kooskõlastuse olek
            properties:
              status: 
                type: string
                description: Staatuse tekstiline kirjeldus
              timestamp:
                type: string
                format: date-time
                description: Staatuse saamise aeg
          description_timestamp:
            type: string
            format: date-time
            description: Süsteemi kohta väljastatava info viimase muutmise aeg
  detailed_system:
    type: object
    description: Süsteemi detailsed andmed. Andmed, mis on peamiselt olulised süsteemi kooskõlastusprotsessis
    properties:
      shortname:
        type: string
        description: Süsteemi lühinimi
      description_timestamp:
        type: string
        format: date-time
        description: Kirje viimase muutmise aeg
      payload:
        type: object
        description: Spetsifitseerimata struktuuriga masinloetav informatsioon süsteemi kohta

