
swagger: '2.0'

info:
  version: "0.0.4"
  title: RIHA-API
  description: Liides andmete avaldamiseks Riigi Infosüsteemi osiste kohta. Iga Riigi Infosüsteemi mõnd osa haldav asutus publitseerib info tema valduses olevate süsteemide ning registrite kohta vähemalt ühes RIHA-API instantsis. Liidese võtmesõnad on rahvusvahelise koosvõime huvides ingliskeelsed. 
  license:
    name: MIT
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /:
    get:
      description: Tagastab nimekirja käesoleva instantsile teadaolevatest infosüsteemidest
      responses:
        '200':
          description: Kõik läks hästi
          schema:
            type: array
            items:
              $ref: '#/definitions/system'

  /{owner}:
    get:
      description: Tagastab info konkreetse omaniku infosüsteemide kohta
      parameters:
        - name: owner
          in: path
          description: Süsteemi omanik
          required: true
          type: string
      responses:
        '200':
          description: Süsteem leidus, info tagastatakse
          schema:
            $ref: '#/definitions/system'
        '404':
          description: Sellenimelist asutust ei leidu
        
  /{owner}/{shortname}:
    get:
      description: Tagastab info konkreetse infosüsteemi kohta. Tegu on ühtlasi süsteemi unikaalse identifikaatoriga
      parameters:
        - name: shortname
          in: path
          description: Viidatava infosüsteemi lühinimi
          required: true
          type: string
        - name: owner
          in: path
          description: Süsteemi omanik
          required: true
          type: string
      responses:
        '200':
          description: Süsteem leidus, info tagastatakse
          schema:
            $ref: '#/definitions/system'
        '404':
          description: Sellenimelist süsteemi ei leidu
  
definitions:
  system:
    type: object
    properties:
      name:
        type: string
        description: Süsteemi täispikk, ametlik, nimi
      shortname:
        type: string
        description: Süsteemi lühinimi

      owner:
        type: object
        properties:
          code:
            type: string
            description: Süsteemi vastutava töötleja registrikood
          name:
            type: string
            description: Süsteemi vastutava töötleja nimi
      documentation:
        type: string
        description: URL, mis viitab süsteemi dokumentatsiooni avalikule asukohale
      system_status:
        type: object
        description: Süsteemi olek
        properties:
          status: 
            type: string
            description: Staatuse tekstiline kirjeldus
          timestamp:
            type: string
            format: date-time
            description: Staatuse saamise aeg
      approval_status:
        type: object
        description: Süsteemi kooskõlastuse olek
        properties:
          status: 
            type: string
            description: Staatuse tekstiline kirjeldus
          timestamp:
            type: string
            format: date-time
            description: Staatuse saamise aeg
      meta:
        type: object
        properties:
          URI:
            type: string
            description: Süsteemi unikaalne URI. Konventsiooni järgi saadakse liites API endpoint'i URI ja lühinimi. GET päring sellele URLile *peab* tagastama süsteemidefinitsiooni objekti.
          timestamp:
            type: string
            format: date-time
            description: Kirjelduse viimase muutmise aeg
